# .github/workflows/CompatHelper.yml
name: CompatHelper
on:
  schedule:
    - cron: '00 00 * * *'
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.SSH_PRIVATE_KEY }}
        run: julia -e 'using CompatHelper; using Pkg; CompatHelper.main(registries = [Pkg.RegistrySpec(name = "General", uuid = "23338594-aafe-5451-b93e-139f81909106", url = "https://github.com/JuliaRegistries/General.git"), Pkg.RegistrySpec(name = "SmartMonitoringSchemes", uuid = "bab96e84-c8f8-4ca3-85f9-6ca5c8f91499", url = "git@github.com:SmartMonitoringSchemes/Registry.git"), Pkg.RegistrySpec(name = "JuliaPOMDP", uuid = "24473b4a-b5e7-11e8-1723-151708197492", url = "http://github.com/JuliaPOMDP/Registry.git")])'
