name: Tests

on: [push]

jobs:
  julia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
      - name: Run tests
        run: julia --project=. --check-bounds=yes -e 'using Pkg; Pkg.test(coverage=true);'
      - name: Upload coverage
        run: julia -e "using Pkg; Pkg.add(\"Coverage\"); using Coverage; Codecov.submit(Codecov.process_folder())"

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: dioptra-io/setup-poetry-action@v1
      - name: Install package
        run: |
          poetry install
          poetry run python -c 'import hdphmm; hdphmm.install()'
      - name: Run tests
        run: poetry run pytest python/
